name: flycar_location
description: A Flutter plugin to easily handle realtime location in iOS and Android. Provides settings for optimizing performance or battery.
version: 0.0.3
author: Bleker <bleker@flycarapp.es>
homepage: https://github.com/blekercm/flycar_location

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: es.flycar.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
        
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  async: ^2.4.1
  test: ^1.14.2
  mockito: 4.1.1
  flutter_test:
    sdk: flutter
  e2e: ^0.3.0
